---
title: "R Notebook"
output: html_notebook
---

Set working directory
```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/anb/Documents/CMEB-Lab/Projects/ML-DRG-PDAC-2025/pdac_feature_generation")
```


```{r}
library(readr)
library(STRINGdb) 

library(dplyr)
#how to install R package "STRINGdb":
#install.packages('BiocManager')
#library(BiocManager)
#BiocManager::install('STRINGdb')

```



```{r}
CC_folderpath <- "local_basal_results/node_tables_GO/local_basal_all_genesetsCC"
MF_folderpath <- "local_basal_results/node_tables_GO/local_basal_all_genesetsMF"
BP_folderpath <- "local_basal_results/node_tables_GO/local_basal_all_genesetsBP"
```


```{r}
# Get the list of file names in the folder
CC_filenames <- list.files(CC_folderpath)
MF_filenames <- list.files(MF_folderpath)
BP_filenames <- list.files(BP_folderpath)

```


```{r}
# create a new STRING_db object
string_db <- STRINGdb$new(version = "12.0", species = 9606, score_threshold = 400, input_directory = "/Users/anb/Downloads/stringdb_database")
```

# Appending the gene symbol column into the node tables
# CC Files
```{r}
# Initialize a list to store the data frames
results_data_frames_CC <- list()


# Loop over the file names
for (CC_filename in CC_filenames) {
  # Construct the file path
  CC_filepath <- file.path(CC_folderpath, CC_filename)
  
  # Read the contents of the file
  CC_filecontents <- read.table(CC_filepath, header = TRUE)
  
  # Rename the STRING ID column 
  names(CC_filecontents)[names(CC_filecontents) == "id"] <- "STRING_id"
  
  #map STRING IDs to Gene Symbols
  CC_genes_mapped <- string_db$add_proteins_description(CC_filecontents)
  
  # Drop columns "protein_size" and "annotation"
  CC_genes_mapped <- CC_genes_mapped[, !(names(CC_genes_mapped) %in% c("protein_size", "annotation"))]
  
  # Rename the Gene Symbol column 
  names(CC_genes_mapped)[names(CC_genes_mapped) == "preferred_name"] <- "hgnc_symbol"
  
  # Rearrange the sequence of columns and Rename column in the data frame
  new_df_CC <- CC_genes_mapped[, c("SUID", "shared", "name", "STRING_id", "hgnc_symbol", "name.1", "selected", "AverageShortestPathLength", "ClusteringCoefficient", "ClosenessCentrality", "IsSingleNode", "PartnerOfMultiEdgedNodePairs", "SelfLoops", "Eccentricity", "Stress", "Degree", "BetweennessCentrality", "NeighborhoodConnectivity", "NumberOfDirectedEdges", "NumberOfUndirectedEdges", "Radiality", "TopologicalCoefficient")]
  
  # Store all results in a data frame
  results_data_frames_CC[[CC_filename]] <- new_df_CC
  
  
}

```


```{r}
## Save modified node tables of the interaction network


# Specify the folder path where you want to save the TSV files
save_folderpath_CC <- "local_basal_results/modified_node_tables_GO/local_basal_all_genesetsCC"


# Loop over the dataframes
for (CC_term_name in names(results_data_frames_CC)) {
  CC_df <- results_data_frames_CC[[CC_term_name]]
  CC_filename <- paste0(CC_term_name)  # Generate the filename
  CC_filepath <- file.path(save_folderpath_CC, CC_filename)  # Create the full filepath
  write.table(CC_df, CC_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```




# MF Files
```{r}
# Initialize a list to store the data frames
results_data_frames_MF <- list()


# Loop over the file names
for (MF_filename in MF_filenames) {
  # Construct the file path
  MF_filepath <- file.path(MF_folderpath, MF_filename)
  
  # Read the contents of the file
  MF_filecontents <- read.table(MF_filepath, header = TRUE)
  
  # Rename the STRING ID column 
  names(MF_filecontents)[names(MF_filecontents) == "id"] <- "STRING_id"
  
  #map STRING IDs to Gene Symbols
  MF_genes_mapped <- string_db$add_proteins_description(MF_filecontents)
  
  # Drop columns "protein_size" and "annotation"
  MF_genes_mapped <- MF_genes_mapped[, !(names(MF_genes_mapped) %in% c("protein_size", "annotation"))]
  
  # Rename the Gene Symbol column 
  names(MF_genes_mapped)[names(MF_genes_mapped) == "preferred_name"] <- "hgnc_symbol"
  
  # Rearrange the sequence of columns and Rename column in the data frame
  new_df_MF <- MF_genes_mapped[, c("SUID", "shared", "name", "STRING_id", "hgnc_symbol", "name.1", "selected", "AverageShortestPathLength", "ClusteringCoefficient", "ClosenessCentrality", "IsSingleNode", "PartnerOfMultiEdgedNodePairs", "SelfLoops", "Eccentricity", "Stress", "Degree", "BetweennessCentrality", "NeighborhoodConnectivity", "NumberOfDirectedEdges", "NumberOfUndirectedEdges", "Radiality", "TopologicalCoefficient")]
  
  # Store all results in a data frame
  results_data_frames_MF[[MF_filename]] <- new_df_MF
  
  
}

```


```{r}
## Save modified node tables of the interaction network


# Specify the folder path where you want to save the TSV files
save_folderpath_MF <- "local_basal_results/modified_node_tables_GO/local_basal_all_genesetsMF"


# Loop over the dataframes
for (MF_term_name in names(results_data_frames_MF)) {
  MF_df <- results_data_frames_MF[[MF_term_name]]
  MF_filename <- paste0(MF_term_name)  # Generate the filename
  MF_filepath <- file.path(save_folderpath_MF, MF_filename)  # Create the full filepath
  write.table(MF_df, MF_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```





# BP Files
```{r}
# Initialize a list to store the data frames
results_data_frames_BP <- list()


# Loop over the file names
for (BP_filename in BP_filenames) {
  # Construct the file path
  BP_filepath <- file.path(BP_folderpath, BP_filename)
  
  # Read the contents of the file
  BP_filecontents <- read.table(BP_filepath, header = TRUE)
  
  # Rename the STRING ID column 
  names(BP_filecontents)[names(BP_filecontents) == "id"] <- "STRING_id"
  
  #map STRING IDs to Gene Symbols
  BP_genes_mapped <- string_db$add_proteins_description(BP_filecontents)
  
  # Drop columns "protein_size" and "annotation"
  BP_genes_mapped <- BP_genes_mapped[, !(names(BP_genes_mapped) %in% c("protein_size", "annotation"))]
  
  # Rename the Gene Symbol column 
  names(BP_genes_mapped)[names(BP_genes_mapped) == "preferred_name"] <- "hgnc_symbol"
  
  # Rearrange the sequence of columns and Rename column in the data frame
  new_df_BP <- BP_genes_mapped[, c("SUID", "shared", "name", "STRING_id", "hgnc_symbol", "name.1", "selected", "AverageShortestPathLength", "ClusteringCoefficient", "ClosenessCentrality", "IsSingleNode", "PartnerOfMultiEdgedNodePairs", "SelfLoops", "Eccentricity", "Stress", "Degree", "BetweennessCentrality", "NeighborhoodConnectivity", "NumberOfDirectedEdges", "NumberOfUndirectedEdges", "Radiality", "TopologicalCoefficient")]
  
  # Store all results in a data frame
  results_data_frames_BP[[BP_filename]] <- new_df_BP
  
  
}

```


```{r}
## Save modified node tables of the interaction network


# Specify the folder path where you want to save the TSV files
save_folderpath_BP <- "local_basal_results/modified_node_tables_GO/local_basal_all_genesetsBP"

# Loop over the dataframes
for (BP_term_name in names(results_data_frames_BP)) {
  BP_df <- results_data_frames_BP[[BP_term_name]]
  BP_filename <- paste0(BP_term_name)  # Generate the filename
  BP_filepath <- file.path(save_folderpath_BP, BP_filename)  # Create the full filepath
  write.table(BP_df, BP_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```






# NDAGs

```{r}
CC_folderpath <- "local_basal_results/node_tables_GO/local_basal_negative_genesetsCC"
MF_folderpath <- "local_basal_results/node_tables_GO/local_basal_negative_genesetsMF"
BP_folderpath <- "local_basal_results/node_tables_GO/local_basal_negative_genesetsBP"
```


```{r}
# Get the list of file names in the folder
CC_filenames <- list.files(CC_folderpath)
MF_filenames <- list.files(MF_folderpath)
BP_filenames <- list.files(BP_folderpath)

```


```{r}
# create a new STRING_db object
string_db <- STRINGdb$new(version = "12.0", species = 9606, score_threshold = 400, input_directory = "/Users/anb/Downloads/stringdb_database")
```

# Appending the gene symbol column into the node tables
# CC Files
```{r}
# Initialize a list to store the data frames
results_data_frames_CC <- list()


# Loop over the file names
for (CC_filename in CC_filenames) {
  # Construct the file path
  CC_filepath <- file.path(CC_folderpath, CC_filename)
  
  # Read the contents of the file
  CC_filecontents <- read.table(CC_filepath, header = TRUE)
  
  # Rename the STRING ID column 
  names(CC_filecontents)[names(CC_filecontents) == "id"] <- "STRING_id"
  
  #map STRING IDs to Gene Symbols
  CC_genes_mapped <- string_db$add_proteins_description(CC_filecontents)
  
  # Drop columns "protein_size" and "annotation"
  CC_genes_mapped <- CC_genes_mapped[, !(names(CC_genes_mapped) %in% c("protein_size", "annotation"))]
  
  # Rename the Gene Symbol column 
  names(CC_genes_mapped)[names(CC_genes_mapped) == "preferred_name"] <- "hgnc_symbol"
  
  # Rearrange the sequence of columns and Rename column in the data frame
  new_df_CC <- CC_genes_mapped[, c("SUID", "shared", "name", "STRING_id", "hgnc_symbol", "name.1", "selected", "AverageShortestPathLength", "ClusteringCoefficient", "ClosenessCentrality", "IsSingleNode", "PartnerOfMultiEdgedNodePairs", "SelfLoops", "Eccentricity", "Stress", "Degree", "BetweennessCentrality", "NeighborhoodConnectivity", "NumberOfDirectedEdges", "NumberOfUndirectedEdges", "Radiality", "TopologicalCoefficient")]
  
  # Store all results in a data frame
  results_data_frames_CC[[CC_filename]] <- new_df_CC
  
  
}

```


```{r}
## Save modified node tables of the interaction network


# Specify the folder path where you want to save the TSV files
save_folderpath_CC <- "local_basal_results/modified_node_tables_GO/local_basal_negative_genesetsCC"


# Loop over the dataframes
for (CC_term_name in names(results_data_frames_CC)) {
  CC_df <- results_data_frames_CC[[CC_term_name]]
  CC_filename <- paste0(CC_term_name)  # Generate the filename
  CC_filepath <- file.path(save_folderpath_CC, CC_filename)  # Create the full filepath
  write.table(CC_df, CC_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```




# MF Files
```{r}
# Initialize a list to store the data frames
results_data_frames_MF <- list()


# Loop over the file names
for (MF_filename in MF_filenames) {
  # Construct the file path
  MF_filepath <- file.path(MF_folderpath, MF_filename)
  
  # Read the contents of the file
  MF_filecontents <- read.table(MF_filepath, header = TRUE)
  
  # Rename the STRING ID column 
  names(MF_filecontents)[names(MF_filecontents) == "id"] <- "STRING_id"
  
  #map STRING IDs to Gene Symbols
  MF_genes_mapped <- string_db$add_proteins_description(MF_filecontents)
  
  # Drop columns "protein_size" and "annotation"
  MF_genes_mapped <- MF_genes_mapped[, !(names(MF_genes_mapped) %in% c("protein_size", "annotation"))]
  
  # Rename the Gene Symbol column 
  names(MF_genes_mapped)[names(MF_genes_mapped) == "preferred_name"] <- "hgnc_symbol"
  
  # Rearrange the sequence of columns and Rename column in the data frame
  new_df_MF <- MF_genes_mapped[, c("SUID", "shared", "name", "STRING_id", "hgnc_symbol", "name.1", "selected", "AverageShortestPathLength", "ClusteringCoefficient", "ClosenessCentrality", "IsSingleNode", "PartnerOfMultiEdgedNodePairs", "SelfLoops", "Eccentricity", "Stress", "Degree", "BetweennessCentrality", "NeighborhoodConnectivity", "NumberOfDirectedEdges", "NumberOfUndirectedEdges", "Radiality", "TopologicalCoefficient")]
  
  # Store all results in a data frame
  results_data_frames_MF[[MF_filename]] <- new_df_MF
  
  
}

```


```{r}
## Save modified node tables of the interaction network


# Specify the folder path where you want to save the TSV files
save_folderpath_MF <- "local_basal_results/modified_node_tables_GO/local_basal_negative_genesetsMF"


# Loop over the dataframes
for (MF_term_name in names(results_data_frames_MF)) {
  MF_df <- results_data_frames_MF[[MF_term_name]]
  MF_filename <- paste0(MF_term_name)  # Generate the filename
  MF_filepath <- file.path(save_folderpath_MF, MF_filename)  # Create the full filepath
  write.table(MF_df, MF_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```





# BP Files
```{r}
# Initialize a list to store the data frames
results_data_frames_BP <- list()


# Loop over the file names
for (BP_filename in BP_filenames) {
  # Construct the file path
  BP_filepath <- file.path(BP_folderpath, BP_filename)
  
  # Read the contents of the file
  BP_filecontents <- read.table(BP_filepath, header = TRUE)
  
  # Rename the STRING ID column 
  names(BP_filecontents)[names(BP_filecontents) == "id"] <- "STRING_id"
  
  #map STRING IDs to Gene Symbols
  BP_genes_mapped <- string_db$add_proteins_description(BP_filecontents)
  
  # Drop columns "protein_size" and "annotation"
  BP_genes_mapped <- BP_genes_mapped[, !(names(BP_genes_mapped) %in% c("protein_size", "annotation"))]
  
  # Rename the Gene Symbol column 
  names(BP_genes_mapped)[names(BP_genes_mapped) == "preferred_name"] <- "hgnc_symbol"
  
  # Rearrange the sequence of columns and Rename column in the data frame
  new_df_BP <- BP_genes_mapped[, c("SUID", "shared", "name", "STRING_id", "hgnc_symbol", "name.1", "selected", "AverageShortestPathLength", "ClusteringCoefficient", "ClosenessCentrality", "IsSingleNode", "PartnerOfMultiEdgedNodePairs", "SelfLoops", "Eccentricity", "Stress", "Degree", "BetweennessCentrality", "NeighborhoodConnectivity", "NumberOfDirectedEdges", "NumberOfUndirectedEdges", "Radiality", "TopologicalCoefficient")]
  
  # Store all results in a data frame
  results_data_frames_BP[[BP_filename]] <- new_df_BP
  
  
}

```


```{r}
## Save modified node tables of the interaction network


# Specify the folder path where you want to save the TSV files
save_folderpath_BP <- "local_basal_results/modified_node_tables_GO/local_basal_negative_genesetsBP"

# Loop over the dataframes
for (BP_term_name in names(results_data_frames_BP)) {
  BP_df <- results_data_frames_BP[[BP_term_name]]
  BP_filename <- paste0(BP_term_name)  # Generate the filename
  BP_filepath <- file.path(save_folderpath_BP, BP_filename)  # Create the full filepath
  write.table(BP_df, BP_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```


# DAGs #




```{r}
CC_folderpath <- "local_basal_results/node_tables_GO/local_basal_positive_genesetsCC"
MF_folderpath <- "local_basal_results/node_tables_GO/local_basal_positive_genesetsMF"
BP_folderpath <- "local_basal_results/node_tables_GO/local_basal_positive_genesetsBP"
```


```{r}
# Get the list of file names in the folder
CC_filenames <- list.files(CC_folderpath)
MF_filenames <- list.files(MF_folderpath)
BP_filenames <- list.files(BP_folderpath)

```


```{r}
# create a new STRING_db object
string_db <- STRINGdb$new(version = "12.0", species = 9606, score_threshold = 400, input_directory = "/Users/anb/Downloads/stringdb_database")
```

# Appending the gene symbol column into the node tables
# CC Files
```{r}
# Initialize a list to store the data frames
results_data_frames_CC <- list()


# Loop over the file names
for (CC_filename in CC_filenames) {
  # Construct the file path
  CC_filepath <- file.path(CC_folderpath, CC_filename)
  
  # Read the contents of the file
  CC_filecontents <- read.table(CC_filepath, header = TRUE)
  
  # Rename the STRING ID column 
  names(CC_filecontents)[names(CC_filecontents) == "id"] <- "STRING_id"
  
  #map STRING IDs to Gene Symbols
  CC_genes_mapped <- string_db$add_proteins_description(CC_filecontents)
  
  # Drop columns "protein_size" and "annotation"
  CC_genes_mapped <- CC_genes_mapped[, !(names(CC_genes_mapped) %in% c("protein_size", "annotation"))]
  
  # Rename the Gene Symbol column 
  names(CC_genes_mapped)[names(CC_genes_mapped) == "preferred_name"] <- "hgnc_symbol"
  
  # Rearrange the sequence of columns and Rename column in the data frame
  new_df_CC <- CC_genes_mapped[, c("SUID", "shared", "name", "STRING_id", "hgnc_symbol", "name.1", "selected", "AverageShortestPathLength", "ClusteringCoefficient", "ClosenessCentrality", "IsSingleNode", "PartnerOfMultiEdgedNodePairs", "SelfLoops", "Eccentricity", "Stress", "Degree", "BetweennessCentrality", "NeighborhoodConnectivity", "NumberOfDirectedEdges", "NumberOfUndirectedEdges", "Radiality", "TopologicalCoefficient")]
  
  # Store all results in a data frame
  results_data_frames_CC[[CC_filename]] <- new_df_CC
  
  
}

```


```{r}
## Save modified node tables of the interaction network


# Specify the folder path where you want to save the TSV files
save_folderpath_CC <- "local_basal_results/modified_node_tables_GO/local_basal_positive_genesetsCC"


# Loop over the dataframes
for (CC_term_name in names(results_data_frames_CC)) {
  CC_df <- results_data_frames_CC[[CC_term_name]]
  CC_filename <- paste0(CC_term_name)  # Generate the filename
  CC_filepath <- file.path(save_folderpath_CC, CC_filename)  # Create the full filepath
  write.table(CC_df, CC_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```




# MF Files
```{r}
# Initialize a list to store the data frames
results_data_frames_MF <- list()


# Loop over the file names
for (MF_filename in MF_filenames) {
  # Construct the file path
  MF_filepath <- file.path(MF_folderpath, MF_filename)
  
  # Read the contents of the file
  MF_filecontents <- read.table(MF_filepath, header = TRUE)
  
  # Rename the STRING ID column 
  names(MF_filecontents)[names(MF_filecontents) == "id"] <- "STRING_id"
  
  #map STRING IDs to Gene Symbols
  MF_genes_mapped <- string_db$add_proteins_description(MF_filecontents)
  
  # Drop columns "protein_size" and "annotation"
  MF_genes_mapped <- MF_genes_mapped[, !(names(MF_genes_mapped) %in% c("protein_size", "annotation"))]
  
  # Rename the Gene Symbol column 
  names(MF_genes_mapped)[names(MF_genes_mapped) == "preferred_name"] <- "hgnc_symbol"
  
  # Rearrange the sequence of columns and Rename column in the data frame
  new_df_MF <- MF_genes_mapped[, c("SUID", "shared", "name", "STRING_id", "hgnc_symbol", "name.1", "selected", "AverageShortestPathLength", "ClusteringCoefficient", "ClosenessCentrality", "IsSingleNode", "PartnerOfMultiEdgedNodePairs", "SelfLoops", "Eccentricity", "Stress", "Degree", "BetweennessCentrality", "NeighborhoodConnectivity", "NumberOfDirectedEdges", "NumberOfUndirectedEdges", "Radiality", "TopologicalCoefficient")]
  
  # Store all results in a data frame
  results_data_frames_MF[[MF_filename]] <- new_df_MF
  
  
}

```


```{r}
## Save modified node tables of the interaction network


# Specify the folder path where you want to save the TSV files
save_folderpath_MF <- "local_basal_results/modified_node_tables_GO/local_basal_positive_genesetsMF"


# Loop over the dataframes
for (MF_term_name in names(results_data_frames_MF)) {
  MF_df <- results_data_frames_MF[[MF_term_name]]
  MF_filename <- paste0(MF_term_name)  # Generate the filename
  MF_filepath <- file.path(save_folderpath_MF, MF_filename)  # Create the full filepath
  write.table(MF_df, MF_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```





# BP Files
```{r}
# Initialize a list to store the data frames
results_data_frames_BP <- list()


# Loop over the file names
for (BP_filename in BP_filenames) {
  # Construct the file path
  BP_filepath <- file.path(BP_folderpath, BP_filename)
  
  # Read the contents of the file
  BP_filecontents <- read.table(BP_filepath, header = TRUE)
  
  # Rename the STRING ID column 
  names(BP_filecontents)[names(BP_filecontents) == "id"] <- "STRING_id"
  
  #map STRING IDs to Gene Symbols
  BP_genes_mapped <- string_db$add_proteins_description(BP_filecontents)
  
  # Drop columns "protein_size" and "annotation"
  BP_genes_mapped <- BP_genes_mapped[, !(names(BP_genes_mapped) %in% c("protein_size", "annotation"))]
  
  # Rename the Gene Symbol column 
  names(BP_genes_mapped)[names(BP_genes_mapped) == "preferred_name"] <- "hgnc_symbol"
  
  # Rearrange the sequence of columns and Rename column in the data frame
  new_df_BP <- BP_genes_mapped[, c("SUID", "shared", "name", "STRING_id", "hgnc_symbol", "name.1", "selected", "AverageShortestPathLength", "ClusteringCoefficient", "ClosenessCentrality", "IsSingleNode", "PartnerOfMultiEdgedNodePairs", "SelfLoops", "Eccentricity", "Stress", "Degree", "BetweennessCentrality", "NeighborhoodConnectivity", "NumberOfDirectedEdges", "NumberOfUndirectedEdges", "Radiality", "TopologicalCoefficient")]
  
  # Store all results in a data frame
  results_data_frames_BP[[BP_filename]] <- new_df_BP
  
  
}

```


```{r}
## Save modified node tables of the interaction network


# Specify the folder path where you want to save the TSV files
save_folderpath_BP <- "local_basal_results/modified_node_tables_GO/local_basal_positive_genesetsBP"

# Loop over the dataframes
for (BP_term_name in names(results_data_frames_BP)) {
  BP_df <- results_data_frames_BP[[BP_term_name]]
  BP_filename <- paste0(BP_term_name)  # Generate the filename
  BP_filepath <- file.path(save_folderpath_BP, BP_filename)  # Create the full filepath
  write.table(BP_df, BP_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```






