---
title: "R Notebook"
output: html_notebook
---

##### GENE SET ENRICHMENT ANALYSIS ######

```{r}
library(affy)
library(limma)
library(tibble)
library(ggplot2)
library(dplyr)
library(ggrepel)
library(readr)
library(limma)
library(pheatmap)
library(pathview)
library(clusterProfiler)
library(enrichplot)
library(europepmc)
library(ggnewscale)
```

```{r}
organism <- "org.Hs.eg.db"
library(organism, character.only = TRUE)
```

This code will create variables in your global environment with names based on the .tsv files in the directory specified by base_path. Please ensure that the file paths are correct and the files exist at those locations. If you’re still encountering issues, please provide more details about the problem.

```{r}
# Define the base file path
base_path <- "/Users/WCVan/Downloads/pdac_analysis_Collision_data/qm_results/filtered-degs/"

# Get the list of all .tsv files in the directory
file_names <- list.files(path = base_path, pattern = "\\.tsv$")

listofdataframes <- as.list(file_names)

# Read the files and assign to variables named after the file names
for (file_name in file_names) {
  # Remove the extension (.tsv) from the file name to use as the variable name
  var_name <- sub("\\.tsv$", "", file_name)
  
  # Read the file
  data <- read.csv(paste0(base_path, file_name), sep = "\t", header = TRUE)
  
  # Assign the data to a variable with the name stored in var_name
  assign(var_name, data, envir = .GlobalEnv)
}
```

```{r}
listofdataframes
```


# All

```{r}
df <- qm_allgenes
```

```{r}
df
```

```{r}
df <- df[!apply(is.na(df) | df$ORF == "", 1, all),]
df$ORF <- sub("/.*", "", df$ORF)
```

```{r}
df
```


```{r}
upreg <- df[df$logFC >= 1, ]
downreg <- df[df$logFC <= -1, ]
```


```{r}
upreg_gene_list <- upreg$ORF
downreg_gene_list <- downreg$ORF
```

```{r}
upreg_gene_list
```


```{r}
# we want the log2 fold change
original_gene_list <- df$logFC

# name the vector
names(original_gene_list) <- df$ORF

# omit any NA values
gene_list <- na.omit(original_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
gene_list <- sort(gene_list, decreasing = TRUE)
```

```{r}
gene_list
```

```{r}
df
```

```{r}
filtdf <- df %>% distinct(ORF, .keep_all = TRUE)
```

```{r}
df <- filtdf
```

```{r}
df
```

```{r}
gse <- gseGO(geneList = gene_list,
             ont = "ALL",
             keyType = "SYMBOL",
             minGSSize = 10,
             maxGSSize = 500,
             pvalueCutoff = 0.05,
             verbose = TRUE,
             OrgDb = organism,
             pAdjustMethod = "fdr")
```

```{r}
genesets <- gse[]
```

```{r}
genesets
genesets$Term <- genesets$ID
genesets$Genes <- genesets$core_enrichment
genesets$FDR <- genesets$p.adjust
genesets$Genes <- gsub("/", ", ", genesets$Genes)
```


```{r}
write_tsv(genesets, file = "/Users/WCVan/Downloads/pdac_analysis_Collision_data/qm_results/clusterprofilerout_GO/GENESET_qm_allgenes.tsv")
write_tsv(df, file = "/Users/WCVan/Downloads/pdac_analysis_Collision_data/qm_results/clusterprofilerout_GO/qm_allgenes.tsv")
```


# DAGs

```{r}
df <- qm_DAGs
```

```{r}
df <- df[!apply(is.na(df) | df$ORF == "", 1, all),]
df$ORF <- sub("/.*", "", df$ORF)
```

```{r}
df
```


```{r}
upreg <- df[df$logFC >= 1, ]
downreg <- df[df$logFC <= -1, ]
```


```{r}
upreg_gene_list <- upreg$ORF
downreg_gene_list <- downreg$ORF
```

```{r}
upreg_gene_list
```


```{r}
# we want the log2 fold change
original_gene_list <- df$logFC

# name the vector
names(original_gene_list) <- df$ORF

# omit any NA values
gene_list <- na.omit(original_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
gene_list <- sort(gene_list, decreasing = TRUE)
```

```{r}
gene_list
```

```{r}
df
```

```{r}
filtdf <- df %>% distinct(ORF, .keep_all = TRUE)
```

```{r}
df <- filtdf
```

```{r}
df
```

```{r}
gse <- gseGO(geneList = gene_list,
             ont = "ALL",
             keyType = "SYMBOL",
             minGSSize = 10,
             maxGSSize = 500,
             pvalueCutoff = 0.05,
             verbose = TRUE,
             OrgDb = organism,
             pAdjustMethod = "fdr")
```

```{r}
genesets <- gse[]
```

```{r}
genesets
genesets$Term <- genesets$ID
genesets$Genes <- genesets$core_enrichment
genesets$FDR <- genesets$p.adjust
genesets$Genes <- gsub("/", ", ", genesets$Genes)
```


```{r}
write_tsv(genesets, file = "/Users/WCVan/Downloads/pdac_analysis_Collision_data/qm_results/clusterprofilerout_GO/GENESET_qm_DAGs.tsv")
write_tsv(df, file = "/Users/WCVan/Downloads/pdac_analysis_Collision_data/qm_results/clusterprofilerout_GO/qm_DAGs.tsv")
```


# NDAGs

```{r}
df <- qm_NDAGs
```

```{r}
df <- df[!apply(is.na(df) | df$ORF == "", 1, all),]
df$ORF <- sub("/.*", "", df$ORF)
```

```{r}
df
```


```{r}
upreg <- df[df$logFC >= 1, ]
downreg <- df[df$logFC <= -1, ]
```


```{r}
upreg_gene_list <- upreg$ORF
downreg_gene_list <- downreg$ORF
```

```{r}
upreg_gene_list
```


```{r}
# we want the log2 fold change
original_gene_list <- df$logFC

# name the vector
names(original_gene_list) <- df$ORF

# omit any NA values
gene_list <- na.omit(original_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
gene_list <- sort(gene_list, decreasing = TRUE)
```

```{r}
gene_list
```

```{r}
df
```

```{r}
filtdf <- df %>% distinct(ORF, .keep_all = TRUE)
```

```{r}
df <- filtdf
```

```{r}
df
```

```{r}
gse <- gseGO(geneList = gene_list,
             ont = "ALL",
             keyType = "SYMBOL",
             minGSSize = 10,
             maxGSSize = 500,
             pvalueCutoff = 0.05,
             verbose = TRUE,
             OrgDb = organism,
             pAdjustMethod = "none")
```

```{r}
genesets <- gse[]
```

```{r}
genesets
genesets$Term <- genesets$ID
genesets$Genes <- genesets$core_enrichment
genesets$FDR <- genesets$p.adjust
genesets$Genes <- gsub("/", ", ", genesets$Genes)
```


```{r}
write_tsv(genesets, file = "/Users/WCVan/Downloads/pdac_analysis_Collision_data/qm_results/clusterprofilerout_GO/GENESET_qm_NDAGs.tsv")
write_tsv(df, file = "/Users/WCVan/Downloads/pdac_analysis_Collision_data/qm_results/clusterprofilerout_GO/qm_NDAGs.tsv")
```