---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(readr)
library(tidyr)
library(readxl)

```


```{r}
UCSF_PDA <- read_excel("/Users/WCVan/Downloads/pdac_analysis_Collision_data/subtype_info.xlsx", sheet = "UCSF PDA")
UCSF_PDA
```


```{r}
UCSF_PDA$`Sample identifier` <- gsub("(.+)", "Microdissected PDA tumor sample (\\1)", UCSF_PDA$`Sample identifier`)
UCSF_PDA
```

```{r}
## Save the table

write.table(UCSF_PDA, "/Users/WCVan/Downloads/pdac_analysis_Collision_data/UCSF_subtype_info.tsv", sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```

```{r}
cell_line_PDA <- read_excel("/Users/WCVan/Downloads/pdac_analysis_Collision_data/subtype_info.xlsx", sheet = "Human PDA cell lines")
cell_line_PDA
```

```{r}
cell_line_PDA$`Sample identifier` <- gsub("(.+)", "cell line: \\1", cell_line_PDA$`Sample identifier`)
cell_line_PDA
```


```{r}
## Save the table

write.table(cell_line_PDA, "/Users/WCVan/Downloads/pdac_analysis_Collision_data/cell_lines_subtype_info.tsv", sep = "\t", row.names = FALSE, col.names = TRUE, quote=FALSE)  # Save as TSV

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```



```{r}
whole_PDA <- read_excel("/Users/WCVan/Downloads/pdac_analysis_Collision_data/subtype_info.xlsx", sheet = "Whole PDA")
whole_PDA
```


```{r}
## Save the table

write.table(whole_PDA, "/Users/WCVan/Downloads/pdac_analysis_Collision_data/wholePDA_subtype_info.tsv", sep = "\t", row.names = FALSE, col.names = TRUE, quote=FALSE)  # Save as TSV

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```



