---
title: "R Notebook"
output: html_notebook
---

Set working directory
```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/anb/Documents/CMEB-Lab/Projects/ML-DRG-PDAC-2025/pdac_feature_generation")
```


```{r}
library(dplyr)
library(readr)
```

## CLASSIC
# ALL #

```{r}
genesets <- read_tsv(file = "local_classic_results/clusterprofilerout_msigdb/GENESET_local_classic_allgenes.tsv")
```


```{r}
#ontology <- as.list(genesets$ID)
```


```{r}
termsandgenes <- genesets[c(1,11)]
```


```{r}
#termsandgenes$ID <- gsub(":", "_", termsandgenes$ID)
```


```{r}
head(termsandgenes)
```


```{r}
# Create an empty list to store dataframes for each term
term_dataframes <- list()

# Iterate over each row in the original dataframe
for (i in 1:nrow(termsandgenes)) {
  terms <- termsandgenes$ID[i]  # Get the term
  genes <- unlist(strsplit(termsandgenes$core_enrichment[i], "/"))  # Get the gene names

  # Create a new dataframe for the current term
  #term_df <- data.frame(Term = terms, Gene = genes)
  term_df <- data.frame(Gene = genes)

  # Add the dataframe to the list
  term_dataframes[[terms]] <- term_df
}

# Now term_dataframes contains separate dataframes for each term
# Access them using term_dataframes$<term_name>

 
```


```{r}
term_dataframes
```


```{r}
# Assuming you have a list of dataframes called term_dataframes
# Modify this list according to your actual dataframes

# Specify the folder path where you want to save the TSV files
folderpath <- "local_classic_results/gsea_msigdb/local_classic_all_genesets"

# Loop over the dataframes
for (term_name in names(term_dataframes)) {
  df <- term_dataframes[[term_name]]
  filename <- paste0(term_name, ".tsv")  # Generate the filename
  filepath <- file.path(folderpath, filename)  # Create the full filepath
  write.table(df, filepath, sep = "\t", row.names = FALSE, col.names = FALSE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```



# DAGs #

```{r}
genesets <- read_tsv(file = "local_classic_results/clusterprofilerout_msigdb/GENESET_local_classic_DAGs.tsv")
```


```{r}
#ontology <- as.list(genesets$ID)
```


```{r}
termsandgenes <- genesets[c(1,11)]
```


```{r}
#termsandgenes$ID <- gsub(":", "_", termsandgenes$ID)
```


```{r}
head(termsandgenes)
```


```{r}
# Create an empty list to store dataframes for each term
term_dataframes <- list()

# Iterate over each row in the original dataframe
for (i in 1:nrow(termsandgenes)) {
  terms <- termsandgenes$ID[i]  # Get the term
  genes <- unlist(strsplit(termsandgenes$core_enrichment[i], "/"))  # Get the gene names

  # Create a new dataframe for the current term
  #term_df <- data.frame(Term = terms, Gene = genes)
  term_df <- data.frame(Gene = genes)

  # Add the dataframe to the list
  term_dataframes[[terms]] <- term_df
}

# Now term_dataframes contains separate dataframes for each term
# Access them using term_dataframes$<term_name>

 
```


```{r}
term_dataframes
```


```{r}
# Assuming you have a list of dataframes called term_dataframes
# Modify this list according to your actual dataframes

# Specify the folder path where you want to save the TSV files
folderpath <- "local_classic_results/gsea_msigdb/local_classic_positive_genesets"

# Loop over the dataframes
for (term_name in names(term_dataframes)) {
  df <- term_dataframes[[term_name]]
  filename <- paste0(term_name, ".tsv")  # Generate the filename
  filepath <- file.path(folderpath, filename)  # Create the full filepath
  write.table(df, filepath, sep = "\t", row.names = FALSE, col.names = FALSE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```



# NDAGs


```{r}
genesets <- read_tsv(file = "local_classic_results/clusterprofilerout_msigdb/GENESET_local_classic_NDAGs.tsv")
```


```{r}
#ontology <- as.list(genesets$ID)
```


```{r}
termsandgenes <- genesets[c(1,11)]
```


```{r}
#termsandgenes$ID <- gsub(":", "_", termsandgenes$ID)
```


```{r}
head(termsandgenes)
```


```{r}
# Create an empty list to store dataframes for each term
term_dataframes <- list()

# Iterate over each row in the original dataframe
for (i in 1:nrow(termsandgenes)) {
  terms <- termsandgenes$ID[i]  # Get the term
  genes <- unlist(strsplit(termsandgenes$core_enrichment[i], "/"))  # Get the gene names

  # Create a new dataframe for the current term
  #term_df <- data.frame(Term = terms, Gene = genes)
  term_df <- data.frame(Gene = genes)

  # Add the dataframe to the list
  term_dataframes[[terms]] <- term_df
}

# Now term_dataframes contains separate dataframes for each term
# Access them using term_dataframes$<term_name>

 
```


```{r}
term_dataframes
```


```{r}
# Assuming you have a list of dataframes called term_dataframes
# Modify this list according to your actual dataframes

# Specify the folder path where you want to save the TSV files
folderpath <- "local_classic_results/gsea_msigdb/local_classic_negative_genesets"

# Loop over the dataframes
for (term_name in names(term_dataframes)) {
  df <- term_dataframes[[term_name]]
  filename <- paste0(term_name, ".tsv")  # Generate the filename
  filepath <- file.path(folderpath, filename)  # Create the full filepath
  write.table(df, filepath, sep = "\t", row.names = FALSE, col.names = FALSE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```



## BASAL

# ALL #

```{r}
genesets <- read_tsv(file = "local_basal_results/clusterprofilerout_msigdb/GENESET_local_basal_allgenes.tsv")
```


```{r}
#ontology <- as.list(genesets$ID)
```


```{r}
termsandgenes <- genesets[c(1,11)]
```


```{r}
#termsandgenes$ID <- gsub(":", "_", termsandgenes$ID)
```


```{r}
head(termsandgenes)
```


```{r}
# Create an empty list to store dataframes for each term
term_dataframes <- list()

# Iterate over each row in the original dataframe
for (i in 1:nrow(termsandgenes)) {
  terms <- termsandgenes$ID[i]  # Get the term
  genes <- unlist(strsplit(termsandgenes$core_enrichment[i], "/"))  # Get the gene names

  # Create a new dataframe for the current term
  #term_df <- data.frame(Term = terms, Gene = genes)
  term_df <- data.frame(Gene = genes)

  # Add the dataframe to the list
  term_dataframes[[terms]] <- term_df
}

# Now term_dataframes contains separate dataframes for each term
# Access them using term_dataframes$<term_name>

 
```


```{r}
term_dataframes
```


```{r}
# Assuming you have a list of dataframes called term_dataframes
# Modify this list according to your actual dataframes

# Specify the folder path where you want to save the TSV files
folderpath <- "local_basal_results/gsea_msigdb/local_basal_all_genesets"

# Loop over the dataframes
for (term_name in names(term_dataframes)) {
  df <- term_dataframes[[term_name]]
  filename <- paste0(term_name, ".tsv")  # Generate the filename
  filepath <- file.path(folderpath, filename)  # Create the full filepath
  write.table(df, filepath, sep = "\t", row.names = FALSE, col.names = FALSE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```



# DAGs #

```{r}
genesets <- read_tsv(file = "local_basal_results/clusterprofilerout_msigdb/GENESET_local_basal_DAGs.tsv")
```


```{r}
#ontology <- as.list(genesets$ID)
```


```{r}
termsandgenes <- genesets[c(1,11)]
```


```{r}
#termsandgenes$ID <- gsub(":", "_", termsandgenes$ID)
```


```{r}
head(termsandgenes)
```


```{r}
# Create an empty list to store dataframes for each term
term_dataframes <- list()

# Iterate over each row in the original dataframe
for (i in 1:nrow(termsandgenes)) {
  terms <- termsandgenes$ID[i]  # Get the term
  genes <- unlist(strsplit(termsandgenes$core_enrichment[i], "/"))  # Get the gene names

  # Create a new dataframe for the current term
  #term_df <- data.frame(Term = terms, Gene = genes)
  term_df <- data.frame(Gene = genes)

  # Add the dataframe to the list
  term_dataframes[[terms]] <- term_df
}

# Now term_dataframes contains separate dataframes for each term
# Access them using term_dataframes$<term_name>

 
```


```{r}
term_dataframes
```


```{r}
# Assuming you have a list of dataframes called term_dataframes
# Modify this list according to your actual dataframes

# Specify the folder path where you want to save the TSV files
folderpath <- "local_basal_results/gsea_msigdb/local_basal_positive_genesets"

# Loop over the dataframes
for (term_name in names(term_dataframes)) {
  df <- term_dataframes[[term_name]]
  filename <- paste0(term_name, ".tsv")  # Generate the filename
  filepath <- file.path(folderpath, filename)  # Create the full filepath
  write.table(df, filepath, sep = "\t", row.names = FALSE, col.names = FALSE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```



# NDAGs


```{r}
genesets <- read_tsv(file = "local_basal_results/clusterprofilerout_msigdb/GENESET_local_basal_NDAGs.tsv")
```


```{r}
#ontology <- as.list(genesets$ID)
```


```{r}
termsandgenes <- genesets[c(1,11)]
```


```{r}
#termsandgenes$ID <- gsub(":", "_", termsandgenes$ID)
```


```{r}
head(termsandgenes)
```


```{r}
# Create an empty list to store dataframes for each term
term_dataframes <- list()

# Iterate over each row in the original dataframe
for (i in 1:nrow(termsandgenes)) {
  terms <- termsandgenes$ID[i]  # Get the term
  genes <- unlist(strsplit(termsandgenes$core_enrichment[i], "/"))  # Get the gene names

  # Create a new dataframe for the current term
  #term_df <- data.frame(Term = terms, Gene = genes)
  term_df <- data.frame(Gene = genes)

  # Add the dataframe to the list
  term_dataframes[[terms]] <- term_df
}

# Now term_dataframes contains separate dataframes for each term
# Access them using term_dataframes$<term_name>

 
```


```{r}
term_dataframes
```


```{r}
# Assuming you have a list of dataframes called term_dataframes
# Modify this list according to your actual dataframes

# Specify the folder path where you want to save the TSV files
folderpath <- "local_basal_results/gsea_msigdb/local_basal_negative_genesets"

# Loop over the dataframes
for (term_name in names(term_dataframes)) {
  df <- term_dataframes[[term_name]]
  filename <- paste0(term_name, ".tsv")  # Generate the filename
  filepath <- file.path(folderpath, filename)  # Create the full filepath
  write.table(df, filepath, sep = "\t", row.names = FALSE, col.names = FALSE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```


