---
title: "R Notebook"
output: html_notebook
---

```{r}

# citations:

# Wickham H, François R, Henry L, Müller K, Vaughan D (2023). _dplyr: A Grammar of Data Manipulation_. R package version 1.1.4, <https://CRAN.R-project.org/package=dplyr>.
  
# Wickham H, Hester J, Bryan J (2024). _readr: Read Rectangular Text Data_. R package version 2.1.5, <https://CRAN.R-project.org/package=readr>.

# Szklarczyk D, Kirsch R, Koutrouli M, Nastou K, Mehryary F, Hachilif R, Annika GL, Fang T, Doncheva NT, Pyysalo S, Bork P, Jensen LJ, von Mering C. 'The STRING database in 2023: protein-protein association networks and functional enrichment analyses for any sequenced genome of interest.' Nucleic Acids Res. 2023 Jan 6;51(D1):D638-646


library(dplyr)
library(readr)
library(STRINGdb) 

#how to install R package "STRINGdb":
#install.packages('BiocManager')
#library(BiocManager)
#BiocManager::install('STRINGdb')

```


```{r}
folderpath <- "/Users/WCVan/Downloads/pdac_analysis_vangie/local_basal_results/node_tables_msigdb/local_basal_negative_genesets"

```


```{r}
# Get the list of file names in the folder
filenames <- list.files(folderpath)

```


# Appending the gene symbol column into the node tables

```{r}
# create a new STRING_db object
string_db <- STRINGdb$new(version = "12.0", species = 9606, score_threshold = 400, input_directory = "/Users/WCVan/Downloads/stringdb_database")

```


```{r}
# Initialize a list to store the data frames
results_data_frames <- list()


# Loop over the file names
for (filename in filenames) {
  # Construct the file path
  filepath <- file.path(folderpath, filename)
  
  # Read the contents of the file
  filecontents <- read.table(filepath, header = TRUE)
  
  # Rename the STRING ID column 
  names(filecontents)[names(filecontents) == "id"] <- "STRING_id"
  
  #map STRING IDs to Gene Symbols
  genes_mapped <- string_db$add_proteins_description(filecontents)
  
  # Drop columns "protein_size" and "annotation"
  genes_mapped <- genes_mapped[, !(names(genes_mapped) %in% c("protein_size", "annotation"))]
  
  # Rename the Gene Symbol column 
  names(genes_mapped)[names(genes_mapped) == "preferred_name"] <- "hgnc_symbol"
  
  # Rearrange the sequence of columns and Rename column in the data frame
  new_df <- genes_mapped[, c("SUID", "shared", "name", "STRING_id", "hgnc_symbol", "name.1", "selected", "AverageShortestPathLength", "ClusteringCoefficient", "ClosenessCentrality", "IsSingleNode", "PartnerOfMultiEdgedNodePairs", "SelfLoops", "Eccentricity", "Stress", "Degree", "BetweennessCentrality", "NeighborhoodConnectivity", "NumberOfDirectedEdges", "NumberOfUndirectedEdges", "Radiality", "TopologicalCoefficient")]
  
  # Store all results in a data frame
  results_data_frames[[filename]] <- new_df
  
  
}

```


```{r}
## Save modified node tables of the interaction network


# Specify the folder path where you want to save the TSV files
save_folderpath <- "/Users/WCVan/Downloads/pdac_analysis_vangie/local_basal_results/modified_node_tables_msigdb/local_basal_negative_genesets"

# Loop over the dataframes
for (term_name in names(results_data_frames)) {
  df <- results_data_frames[[term_name]]
  filename <- paste0(term_name)  # Generate the filename
  filepath <- file.path(save_folderpath, filename)  # Create the full filepath
  write.table(df, filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```






