---
title: "R Notebook"
output: html_notebook
---

Set working directory
```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/anb/Documents/CMEB-Lab/Projects/ML-DRG-PDAC-2025/pdac_feature_generation")
```


```{r}
library(dplyr)
library(readr)
library(rbioapi)

#how to install R package "rbioapi":
#install.packages('BiocManager')
#library(BiocManager)
#BiocManager::install('rbioapi')
```

# CLASSIC
## ALL # 

```{r}
folderpath <- "local_classic_results/gsea_msigdb/local_classic_all_genesets"
```


```{r}
# Get the list of file names in the folder
filenames <- list.files(folderpath)
```


Mapping String ID

```{r}
# Initialize a list to store the data frames
mapped_id <- list()

```


```{r}
# Loop over the file names
for (filename in filenames) {
  # Construct the file path
  filepath <- file.path(folderpath, filename)
  
  # Read the contents of the file
  filecontents <- read.delim(filepath, header = FALSE)
  
  # Perform operations on the file contents
  # Add a column name
  names(filecontents) <- paste0("genes_symbol")
  
  # Map genes IDs to STRING IDs
  proteins_mapped <- rba_string_map_ids(ids = filecontents$genes_symbol, species = 9606)
  
  # Select "queryItem" column and "stringId" column
  proteins_mapped <- proteins_mapped[, c("queryItem", "stringId")]
  
  # Rename the columns
  names(proteins_mapped)[names(proteins_mapped) == "queryItem"] <- "genes_symbol"
  names(proteins_mapped)[names(proteins_mapped) == "stringId"] <- "STRING_id"
  
  
  # Store the mapped ids in a data frame
  mapped_id[[filename]] <- proteins_mapped

  
}
```


```{r}
##Save STRING Mapped ID

# Specify the folder path where you want to save the TSV files
save_folderpath <- "local_classic_results/mapped_ids_msigdb/local_classic_all_genesets"

# Loop over the dataframes
for (term_name in names(mapped_id)) {
  df <- mapped_id[[term_name]]
  filename <- paste0(term_name)  # Generate the filename
  filepath <- file.path(save_folderpath, filename)  # Create the full filepath
  write.table(df, filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")


```




## NDAGs # 

```{r}
folderpath <- "local_classic_results/gsea_msigdb/local_classic_negative_genesets"
```


```{r}
# Get the list of file names in the folder
filenames <- list.files(folderpath)
```


Mapping String ID

```{r}
# Initialize a list to store the data frames
mapped_id <- list()

```


```{r}
# Loop over the file names
for (filename in filenames) {
  # Construct the file path
  filepath <- file.path(folderpath, filename)
  
  # Read the contents of the file
  filecontents <- read.delim(filepath, header = FALSE)
  
  # Perform operations on the file contents
  # Add a column name
  names(filecontents) <- paste0("genes_symbol")
  
  # Map genes IDs to STRING IDs
  proteins_mapped <- rba_string_map_ids(ids = filecontents$genes_symbol, species = 9606)
  
  # Select "queryItem" column and "stringId" column
  proteins_mapped <- proteins_mapped[, c("queryItem", "stringId")]
  
  # Rename the columns
  names(proteins_mapped)[names(proteins_mapped) == "queryItem"] <- "genes_symbol"
  names(proteins_mapped)[names(proteins_mapped) == "stringId"] <- "STRING_id"
  
  
  # Store the mapped ids in a data frame
  mapped_id[[filename]] <- proteins_mapped

  
}
```


```{r}
##Save STRING Mapped ID

# Specify the folder path where you want to save the TSV files
save_folderpath <- "local_classic_results/mapped_ids_msigdb/local_classic_negative_genesets"

# Loop over the dataframes
for (term_name in names(mapped_id)) {
  df <- mapped_id[[term_name]]
  filename <- paste0(term_name)  # Generate the filename
  filepath <- file.path(save_folderpath, filename)  # Create the full filepath
  write.table(df, filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")


```





## DAGs # 

```{r}
folderpath <- "local_classic_results/gsea_msigdb/local_classic_positive_genesets"
```


```{r}
# Get the list of file names in the folder
filenames <- list.files(folderpath)
```


Mapping String ID

```{r}
# Initialize a list to store the data frames
mapped_id <- list()

```


```{r}
# Loop over the file names
for (filename in filenames) {
  # Construct the file path
  filepath <- file.path(folderpath, filename)
  
  # Read the contents of the file
  filecontents <- read.delim(filepath, header = FALSE)
  
  # Perform operations on the file contents
  # Add a column name
  names(filecontents) <- paste0("genes_symbol")
  
  # Map genes IDs to STRING IDs
  proteins_mapped <- rba_string_map_ids(ids = filecontents$genes_symbol, species = 9606)
  
  # Select "queryItem" column and "stringId" column
  proteins_mapped <- proteins_mapped[, c("queryItem", "stringId")]
  
  # Rename the columns
  names(proteins_mapped)[names(proteins_mapped) == "queryItem"] <- "genes_symbol"
  names(proteins_mapped)[names(proteins_mapped) == "stringId"] <- "STRING_id"
  
  
  # Store the mapped ids in a data frame
  mapped_id[[filename]] <- proteins_mapped

  
}
```


```{r}
##Save STRING Mapped ID

# Specify the folder path where you want to save the TSV files
save_folderpath <- "local_classic_results/mapped_ids_msigdb/local_classic_positive_genesets"

# Loop over the dataframes
for (term_name in names(mapped_id)) {
  df <- mapped_id[[term_name]]
  filename <- paste0(term_name)  # Generate the filename
  filepath <- file.path(save_folderpath, filename)  # Create the full filepath
  write.table(df, filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")


```










## BASAL

# BASAL
## ALL # 

```{r}
folderpath <- "local_basal_results/gsea_msigdb/local_basal_all_genesets"
```


```{r}
# Get the list of file names in the folder
filenames <- list.files(folderpath)
```


Mapping String ID

```{r}
# Initialize a list to store the data frames
mapped_id <- list()

```


```{r}
# Loop over the file names
for (filename in filenames) {
  # Construct the file path
  filepath <- file.path(folderpath, filename)
  
  # Read the contents of the file
  filecontents <- read.delim(filepath, header = FALSE)
  
  # Perform operations on the file contents
  # Add a column name
  names(filecontents) <- paste0("genes_symbol")
  
  # Map genes IDs to STRING IDs
  proteins_mapped <- rba_string_map_ids(ids = filecontents$genes_symbol, species = 9606)
  
  # Select "queryItem" column and "stringId" column
  proteins_mapped <- proteins_mapped[, c("queryItem", "stringId")]
  
  # Rename the columns
  names(proteins_mapped)[names(proteins_mapped) == "queryItem"] <- "genes_symbol"
  names(proteins_mapped)[names(proteins_mapped) == "stringId"] <- "STRING_id"
  
  
  # Store the mapped ids in a data frame
  mapped_id[[filename]] <- proteins_mapped

  
}
```


```{r}
##Save STRING Mapped ID

# Specify the folder path where you want to save the TSV files
save_folderpath <- "local_basal_results/mapped_ids_msigdb/local_basal_all_genesets"

# Loop over the dataframes
for (term_name in names(mapped_id)) {
  df <- mapped_id[[term_name]]
  filename <- paste0(term_name)  # Generate the filename
  filepath <- file.path(save_folderpath, filename)  # Create the full filepath
  write.table(df, filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")


```




## NDAGs # 

```{r}
folderpath <- "local_basal_results/gsea_msigdb/local_basal_negative_genesets"
```


```{r}
# Get the list of file names in the folder
filenames <- list.files(folderpath)
```


Mapping String ID

```{r}
# Initialize a list to store the data frames
mapped_id <- list()

```


```{r}
# Loop over the file names
for (filename in filenames) {
  # Construct the file path
  filepath <- file.path(folderpath, filename)
  
  # Read the contents of the file
  filecontents <- read.delim(filepath, header = FALSE)
  
  # Perform operations on the file contents
  # Add a column name
  names(filecontents) <- paste0("genes_symbol")
  
  # Map genes IDs to STRING IDs
  proteins_mapped <- rba_string_map_ids(ids = filecontents$genes_symbol, species = 9606)
  
  # Select "queryItem" column and "stringId" column
  proteins_mapped <- proteins_mapped[, c("queryItem", "stringId")]
  
  # Rename the columns
  names(proteins_mapped)[names(proteins_mapped) == "queryItem"] <- "genes_symbol"
  names(proteins_mapped)[names(proteins_mapped) == "stringId"] <- "STRING_id"
  
  
  # Store the mapped ids in a data frame
  mapped_id[[filename]] <- proteins_mapped

  
}
```


```{r}
##Save STRING Mapped ID

# Specify the folder path where you want to save the TSV files
save_folderpath <- "local_basal_results/mapped_ids_msigdb/local_basal_negative_genesets"

# Loop over the dataframes
for (term_name in names(mapped_id)) {
  df <- mapped_id[[term_name]]
  filename <- paste0(term_name)  # Generate the filename
  filepath <- file.path(save_folderpath, filename)  # Create the full filepath
  write.table(df, filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")


```



## DAGs # 

```{r}
folderpath <- "local_basal_results/gsea_msigdb/local_basal_positive_genesets"
```


```{r}
# Get the list of file names in the folder
filenames <- list.files(folderpath)
```


Mapping String ID

```{r}
# Initialize a list to store the data frames
mapped_id <- list()

```


```{r}
# Loop over the file names
for (filename in filenames) {
  # Construct the file path
  filepath <- file.path(folderpath, filename)
  
  # Read the contents of the file
  filecontents <- read.delim(filepath, header = FALSE)
  
  # Perform operations on the file contents
  # Add a column name
  names(filecontents) <- paste0("genes_symbol")
  
  # Map genes IDs to STRING IDs
  proteins_mapped <- rba_string_map_ids(ids = filecontents$genes_symbol, species = 9606)
  
  # Select "queryItem" column and "stringId" column
  proteins_mapped <- proteins_mapped[, c("queryItem", "stringId")]
  
  # Rename the columns
  names(proteins_mapped)[names(proteins_mapped) == "queryItem"] <- "genes_symbol"
  names(proteins_mapped)[names(proteins_mapped) == "stringId"] <- "STRING_id"
  
  
  # Store the mapped ids in a data frame
  mapped_id[[filename]] <- proteins_mapped

  
}
```


```{r}
##Save STRING Mapped ID

# Specify the folder path where you want to save the TSV files
save_folderpath <- "local_basal_results/mapped_ids_msigdb/local_basal_positive_genesets"

# Loop over the dataframes
for (term_name in names(mapped_id)) {
  df <- mapped_id[[term_name]]
  filename <- paste0(term_name)  # Generate the filename
  filepath <- file.path(save_folderpath, filename)  # Create the full filepath
  write.table(df, filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")


```


