---
title: "R Notebook"
output: html_notebook
---


Set working directory
```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/anb/Documents/CMEB-Lab/Projects/ML-DRG-PDAC-2025/pdac_feature_generation")
```


```{r}
library(dplyr)
library(readr)
library(rbioapi)

#how to install R package "rbioapi":
#install.packages('BiocManager')
#library(BiocManager)
#BiocManager::install('rbioapi')
```





```{r}
CC_folderpath <- "local_classic_results/gsea_GO/local_classic_all_genesetsCC"
MF_folderpath <- "local_classic_results/gsea_GO/local_classic_all_genesetsMF"
BP_folderpath <- "local_classic_results/gsea_GO/local_classic_all_genesetsBP"
```


```{r}
# Get the list of file names in the folder
CC_filenames <- list.files(CC_folderpath)
MF_filenames <- list.files(MF_folderpath)
BP_filenames <- list.files(BP_folderpath)
```


#Mapping String ID
#CC Files
```{r}
# Initialize a list to store the data frames
CC_mapped_id <- list()

# Loop over the file names
for (CC_filename in CC_filenames) {
  # Construct the file path
  CC_filepath <- file.path(CC_folderpath, CC_filename)
  
  # Read the contents of the file
  CC_filecontents <- read.delim(CC_filepath, header = FALSE)
  
  # Perform operations on the file contents
  # Add a column name
  names(CC_filecontents) <- paste0("genes_symbol")
  
  # Map genes IDs to STRING IDs
  CC_proteins_mapped <- rba_string_map_ids(ids = CC_filecontents$genes_symbol, species = 9606)
  
  # Select "queryItem" column and "stringId" column
  CC_proteins_mapped <- CC_proteins_mapped[, c("queryItem", "stringId")]
  
  # Rename the columns
  names(CC_proteins_mapped)[names(CC_proteins_mapped) == "queryItem"] <- "genes_symbol"
  names(CC_proteins_mapped)[names(CC_proteins_mapped) == "stringId"] <- "STRING_id"
  
  
  # Store the mapped ids in a data frame
  CC_mapped_id[[CC_filename]] <- CC_proteins_mapped

  
}
```


```{r}
##Save STRING Mapped ID

# Specify the folder path where you want to save the TSV files
CC_save_folderpath <- "local_classic_results/mapped_ids_GO/local_classic_all_genesetsCC"

# Loop over the dataframes
for (CC_term_name in names(CC_mapped_id)) {
  CC_df <- CC_mapped_id[[CC_term_name]]
  CC_filename <- paste0(CC_term_name)  # Generate the filename
  CC_filepath <- file.path(CC_save_folderpath, CC_filename)  # Create the full filepath
  write.table(CC_df, CC_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")


```



#MF Files
```{r}
# Initialize a list to store the data frames
MF_mapped_id <- list()

# Loop over the file names
for (MF_filename in MF_filenames) {
  # Construct the file path
  MF_filepath <- file.path(MF_folderpath, MF_filename)
  
  # Read the contents of the file
  MF_filecontents <- read.delim(MF_filepath, header = FALSE)
  
  # Perform operations on the file contents
  # Add a column name
  names(MF_filecontents) <- paste0("genes_symbol")
  
  # Map genes IDs to STRING IDs
  MF_proteins_mapped <- rba_string_map_ids(ids = MF_filecontents$genes_symbol, species = 9606)
  
  # Select "queryItem" column and "stringId" column
  MF_proteins_mapped <- MF_proteins_mapped[, c("queryItem", "stringId")]
  
  # Rename the columns
  names(MF_proteins_mapped)[names(MF_proteins_mapped) == "queryItem"] <- "genes_symbol"
  names(MF_proteins_mapped)[names(MF_proteins_mapped) == "stringId"] <- "STRING_id"
  
  
  # Store the mapped ids in a data frame
  MF_mapped_id[[MF_filename]] <- MF_proteins_mapped

  
}
```


```{r}
##Save STRING Mapped ID

# Specify the folder path where you want to save the TSV files
MF_save_folderpath <- "local_classic_results/mapped_ids_GO/local_classic_all_genesetsMF"

# Loop over the dataframes
for (MF_term_name in names(MF_mapped_id)) {
  MF_df <- MF_mapped_id[[MF_term_name]]
  MF_filename <- paste0(MF_term_name)  # Generate the filename
  MF_filepath <- file.path(MF_save_folderpath, MF_filename)  # Create the full filepath
  write.table(MF_df, MF_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")


```


#BP Files
```{r}
# Initialize a list to store the data frames
BP_mapped_id <- list()

# Loop over the file names
for (BP_filename in BP_filenames) {
  # Construct the file path
  BP_filepath <- file.path(BP_folderpath, BP_filename)
  
  # Read the contents of the file
  BP_filecontents <- read.delim(BP_filepath, header = FALSE)
  
  # Perform operations on the file contents
  # Add a column name
  names(BP_filecontents) <- paste0("genes_symbol")
  
  # Map genes IDs to STRING IDs
  BP_proteins_mapped <- rba_string_map_ids(ids = BP_filecontents$genes_symbol, species = 9606)
  
  # Select "queryItem" column and "stringId" column
  BP_proteins_mapped <- BP_proteins_mapped[, c("queryItem", "stringId")]
  
  # Rename the columns
  names(BP_proteins_mapped)[names(BP_proteins_mapped) == "queryItem"] <- "genes_symbol"
  names(BP_proteins_mapped)[names(BP_proteins_mapped) == "stringId"] <- "STRING_id"
  
  
  # Store the mapped ids in a data frame
  BP_mapped_id[[BP_filename]] <- BP_proteins_mapped

  
}
```



```{r}
##Save STRING Mapped ID

# Specify the folder path where you want to save the TSV files
BP_save_folderpath <- "local_classic_results/mapped_ids_GO/local_classic_all_genesetsBP"

# Loop over the dataframes
for (BP_term_name in names(BP_mapped_id)) {
  BP_df <- BP_mapped_id[[BP_term_name]]
  BP_filename <- paste0(BP_term_name)  # Generate the filename
  BP_filepath <- file.path(BP_save_folderpath, BP_filename)  # Create the full filepath
  write.table(BP_df, BP_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```



## classic NDAGs ##


```{r}
CC_folderpath <- "local_classic_results/gsea_GO/local_classic_negative_genesetsCC"
MF_folderpath <- "local_classic_results/gsea_GO/local_classic_negative_genesetsMF"
BP_folderpath <- "local_classic_results/gsea_GO/local_classic_negative_genesetsBP"
```


```{r}
# Get the list of file names in the folder
CC_filenames <- list.files(CC_folderpath)
MF_filenames <- list.files(MF_folderpath)
BP_filenames <- list.files(BP_folderpath)
```


#Mapping String ID
#CC Files
```{r}
# Initialize a list to store the data frames
CC_mapped_id <- list()

# Loop over the file names
for (CC_filename in CC_filenames) {
  # Construct the file path
  CC_filepath <- file.path(CC_folderpath, CC_filename)
  
  # Read the contents of the file
  CC_filecontents <- read.delim(CC_filepath, header = FALSE)
  
  # Perform operations on the file contents
  # Add a column name
  names(CC_filecontents) <- paste0("genes_symbol")
  
  # Map genes IDs to STRING IDs
  CC_proteins_mapped <- rba_string_map_ids(ids = CC_filecontents$genes_symbol, species = 9606)
  
  # Select "queryItem" column and "stringId" column
  CC_proteins_mapped <- CC_proteins_mapped[, c("queryItem", "stringId")]
  
  # Rename the columns
  names(CC_proteins_mapped)[names(CC_proteins_mapped) == "queryItem"] <- "genes_symbol"
  names(CC_proteins_mapped)[names(CC_proteins_mapped) == "stringId"] <- "STRING_id"
  
  
  # Store the mapped ids in a data frame
  CC_mapped_id[[CC_filename]] <- CC_proteins_mapped

  
}
```


```{r}
##Save STRING Mapped ID

# Specify the folder path where you want to save the TSV files
CC_save_folderpath <- "local_classic_results/mapped_ids_GO/local_classic_negative_genesetsCC"

# Loop over the dataframes
for (CC_term_name in names(CC_mapped_id)) {
  CC_df <- CC_mapped_id[[CC_term_name]]
  CC_filename <- paste0(CC_term_name)  # Generate the filename
  CC_filepath <- file.path(CC_save_folderpath, CC_filename)  # Create the full filepath
  write.table(CC_df, CC_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")


```



#MF Files
```{r}
# Initialize a list to store the data frames
MF_mapped_id <- list()

# Loop over the file names
for (MF_filename in MF_filenames) {
  # Construct the file path
  MF_filepath <- file.path(MF_folderpath, MF_filename)
  
  # Read the contents of the file
  MF_filecontents <- read.delim(MF_filepath, header = FALSE)
  
  # Perform operations on the file contents
  # Add a column name
  names(MF_filecontents) <- paste0("genes_symbol")
  
  # Map genes IDs to STRING IDs
  MF_proteins_mapped <- rba_string_map_ids(ids = MF_filecontents$genes_symbol, species = 9606)
  
  # Select "queryItem" column and "stringId" column
  MF_proteins_mapped <- MF_proteins_mapped[, c("queryItem", "stringId")]
  
  # Rename the columns
  names(MF_proteins_mapped)[names(MF_proteins_mapped) == "queryItem"] <- "genes_symbol"
  names(MF_proteins_mapped)[names(MF_proteins_mapped) == "stringId"] <- "STRING_id"
  
  
  # Store the mapped ids in a data frame
  MF_mapped_id[[MF_filename]] <- MF_proteins_mapped

  
}
```


```{r}
##Save STRING Mapped ID

# Specify the folder path where you want to save the TSV files
MF_save_folderpath <- "local_classic_results/mapped_ids_GO/local_classic_negative_genesetsMF"

# Loop over the dataframes
for (MF_term_name in names(MF_mapped_id)) {
  MF_df <- MF_mapped_id[[MF_term_name]]
  MF_filename <- paste0(MF_term_name)  # Generate the filename
  MF_filepath <- file.path(MF_save_folderpath, MF_filename)  # Create the full filepath
  write.table(MF_df, MF_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")


```


#BP Files
```{r}
# Initialize a list to store the data frames
BP_mapped_id <- list()

# Loop over the file names
for (BP_filename in BP_filenames) {
  # Construct the file path
  BP_filepath <- file.path(BP_folderpath, BP_filename)
  
  # Read the contents of the file
  BP_filecontents <- read.delim(BP_filepath, header = FALSE)
  
  # Perform operations on the file contents
  # Add a column name
  names(BP_filecontents) <- paste0("genes_symbol")
  
  # Map genes IDs to STRING IDs
  BP_proteins_mapped <- rba_string_map_ids(ids = BP_filecontents$genes_symbol, species = 9606)
  
  # Select "queryItem" column and "stringId" column
  BP_proteins_mapped <- BP_proteins_mapped[, c("queryItem", "stringId")]
  
  # Rename the columns
  names(BP_proteins_mapped)[names(BP_proteins_mapped) == "queryItem"] <- "genes_symbol"
  names(BP_proteins_mapped)[names(BP_proteins_mapped) == "stringId"] <- "STRING_id"
  
  
  # Store the mapped ids in a data frame
  BP_mapped_id[[BP_filename]] <- BP_proteins_mapped

  
}
```



```{r}
##Save STRING Mapped ID

# Specify the folder path where you want to save the TSV files
BP_save_folderpath <- "local_classic_results/mapped_ids_GO/local_classic_negative_genesetsBP"

# Loop over the dataframes
for (BP_term_name in names(BP_mapped_id)) {
  BP_df <- BP_mapped_id[[BP_term_name]]
  BP_filename <- paste0(BP_term_name)  # Generate the filename
  BP_filepath <- file.path(BP_save_folderpath, BP_filename)  # Create the full filepath
  write.table(BP_df, BP_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```



## classic DAGs ##


```{r}
CC_folderpath <- "local_classic_results/gsea_GO/local_classic_positive_genesetsCC"
MF_folderpath <- "local_classic_results/gsea_GO/local_classic_positive_genesetsMF"
BP_folderpath <- "local_classic_results/gsea_GO/local_classic_positive_genesetsBP"
```


```{r}
# Get the list of file names in the folder
CC_filenames <- list.files(CC_folderpath)
MF_filenames <- list.files(MF_folderpath)
BP_filenames <- list.files(BP_folderpath)
```


#Mapping String ID
#CC Files
```{r}
# Initialize a list to store the data frames
CC_mapped_id <- list()

# Loop over the file names
for (CC_filename in CC_filenames) {
  # Construct the file path
  CC_filepath <- file.path(CC_folderpath, CC_filename)
  
  # Read the contents of the file
  CC_filecontents <- read.delim(CC_filepath, header = FALSE)
  
  # Perform operations on the file contents
  # Add a column name
  names(CC_filecontents) <- paste0("genes_symbol")
  
  # Map genes IDs to STRING IDs
  CC_proteins_mapped <- rba_string_map_ids(ids = CC_filecontents$genes_symbol, species = 9606)
  
  # Select "queryItem" column and "stringId" column
  CC_proteins_mapped <- CC_proteins_mapped[, c("queryItem", "stringId")]
  
  # Rename the columns
  names(CC_proteins_mapped)[names(CC_proteins_mapped) == "queryItem"] <- "genes_symbol"
  names(CC_proteins_mapped)[names(CC_proteins_mapped) == "stringId"] <- "STRING_id"
  
  
  # Store the mapped ids in a data frame
  CC_mapped_id[[CC_filename]] <- CC_proteins_mapped

  
}
```


```{r}
##Save STRING Mapped ID

# Specify the folder path where you want to save the TSV files
CC_save_folderpath <- "local_classic_results/mapped_ids_GO/local_classic_positive_genesetsCC"

# Loop over the dataframes
for (CC_term_name in names(CC_mapped_id)) {
  CC_df <- CC_mapped_id[[CC_term_name]]
  CC_filename <- paste0(CC_term_name)  # Generate the filename
  CC_filepath <- file.path(CC_save_folderpath, CC_filename)  # Create the full filepath
  write.table(CC_df, CC_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")


```



#MF Files
```{r}
# Initialize a list to store the data frames
MF_mapped_id <- list()

# Loop over the file names
for (MF_filename in MF_filenames) {
  # Construct the file path
  MF_filepath <- file.path(MF_folderpath, MF_filename)
  
  # Read the contents of the file
  MF_filecontents <- read.delim(MF_filepath, header = FALSE)
  
  # Perform operations on the file contents
  # Add a column name
  names(MF_filecontents) <- paste0("genes_symbol")
  
  # Map genes IDs to STRING IDs
  MF_proteins_mapped <- rba_string_map_ids(ids = MF_filecontents$genes_symbol, species = 9606)
  
  # Select "queryItem" column and "stringId" column
  MF_proteins_mapped <- MF_proteins_mapped[, c("queryItem", "stringId")]
  
  # Rename the columns
  names(MF_proteins_mapped)[names(MF_proteins_mapped) == "queryItem"] <- "genes_symbol"
  names(MF_proteins_mapped)[names(MF_proteins_mapped) == "stringId"] <- "STRING_id"
  
  
  # Store the mapped ids in a data frame
  MF_mapped_id[[MF_filename]] <- MF_proteins_mapped

  
}
```


```{r}
##Save STRING Mapped ID

# Specify the folder path where you want to save the TSV files
MF_save_folderpath <- "local_classic_results/mapped_ids_GO/local_classic_positive_genesetsMF"

# Loop over the dataframes
for (MF_term_name in names(MF_mapped_id)) {
  MF_df <- MF_mapped_id[[MF_term_name]]
  MF_filename <- paste0(MF_term_name)  # Generate the filename
  MF_filepath <- file.path(MF_save_folderpath, MF_filename)  # Create the full filepath
  write.table(MF_df, MF_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")


```


#BP Files
```{r}
# Initialize a list to store the data frames
BP_mapped_id <- list()

# Loop over the file names
for (BP_filename in BP_filenames) {
  # Construct the file path
  BP_filepath <- file.path(BP_folderpath, BP_filename)
  
  # Read the contents of the file
  BP_filecontents <- read.delim(BP_filepath, header = FALSE)
  
  # Perform operations on the file contents
  # Add a column name
  names(BP_filecontents) <- paste0("genes_symbol")
  
  # Map genes IDs to STRING IDs
  BP_proteins_mapped <- rba_string_map_ids(ids = BP_filecontents$genes_symbol, species = 9606)
  
  # Select "queryItem" column and "stringId" column
  BP_proteins_mapped <- BP_proteins_mapped[, c("queryItem", "stringId")]
  
  # Rename the columns
  names(BP_proteins_mapped)[names(BP_proteins_mapped) == "queryItem"] <- "genes_symbol"
  names(BP_proteins_mapped)[names(BP_proteins_mapped) == "stringId"] <- "STRING_id"
  
  
  # Store the mapped ids in a data frame
  BP_mapped_id[[BP_filename]] <- BP_proteins_mapped

  
}
```



```{r}
##Save STRING Mapped ID

# Specify the folder path where you want to save the TSV files
BP_save_folderpath <- "local_classic_results/mapped_ids_GO/local_classic_positive_genesetsBP"

# Loop over the dataframes
for (BP_term_name in names(BP_mapped_id)) {
  BP_df <- BP_mapped_id[[BP_term_name]]
  BP_filename <- paste0(BP_term_name)  # Generate the filename
  BP_filepath <- file.path(BP_save_folderpath, BP_filename)  # Create the full filepath
  write.table(BP_df, BP_filepath, sep = "\t", row.names = TRUE, col.names = TRUE, quote=FALSE)  # Save as TSV
}

cat("Dataframes successfully saved with corresponding names as TSV files.\n")
```


